lattes_site/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin
from os import path
from flask_bootstrap import Bootstrap


db = SQLAlchemy()
admin = Admin()

def create_app(): 

    # Configs 
    app = Flask(__name__)
    app.config["SECRET_KEY"] =  "secret"
    app.secret_key = "shhhh e secreto"
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///database.db"
    Bootstrap(app)


    db.init_app(app)
    admin.init_app(app)


    #Routes/Views 
    from .routes import views 
    app.register_blueprint(views, url_prefix="/")
    
    #Database
    from . import base
    create_db(app)

    return app

#Create de Database
def create_db(app):
    if not path.exists('lattes_site/database.db'):
        db.create_all(app=app)
        print("Created Database")

lattes_site/routes.py
from flask import Blueprint, render_template, redirect, request, session, flash
from flask.helpers import  url_for
from . import db, admin
from flask_admin.contrib.sqla import ModelView
from lattes_site.base import User
from .form import Form


views =  Blueprint('views', __name__,)


@views.route('/', methods=["GET", "POST"])
def home():
    
    #Pega as informações no formulário de busca e envia através de uma sessão para as views.user
    if request.method == "POST": 
        user = request.form["search_form"]
        session["user"] =  user 
        return redirect (url_for("views.user"))

    return render_template('index.html')

@views.route('/register', methods=['GET', 'POST'])
def register():

    forms = Form() 
    
    #Verifica se está tudo válido nos forms e não ocorrou nenhum erro
    #após salva as informações no backend e manda um feedback para o usuário(flash message)
    try:
        if forms.validate_on_submit(): 

                user = User(forms.name.data, forms.email.data, forms.formation.data, forms.course.data, forms.idiom.data, forms.address.data)
                db.session.add(user)
                db.session.commit()
                flash("The informations are registred!")
                return redirect("/")
    except:
        flash("Something goes wrong")
        return redirect("/register")

    return render_template('register.html', form=forms)

@views.route('/user')
def user():

    #Verifica se há usuário na sessão, pesquisa o usuário no banco de dados e depois retorna as informações
    if "user" in session: 
        user = User.query.filter_by(name=session["user"]).first()
        if user:
            return render_template("user.html", user = user)
        return redirect("/") 


# Adiciona uma view Admin

admin.add_view(ModelView(User, db.session,))

lattes_site/templates/base.html
<!DOCTYPE html>

<head>

{% block head %}

  <!-- Links das páginas Static CSS e Bootstrap  -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
  <title>{% block title %} Lattes {% endblock %}</title>
  <link rel="icon" type="imagem/png" href="{{url_for('static', filename='images/icons/icon-lattes.png')}}"/>

{% endblock %}
</head>

{% block navbar %} 

<!-- NAVBAR -->

<nav class="navbar navbar-expand-lg p-3">
    <div class="container-fluid">
      <img src="{{url_for('static', filename='images/icons/icon_home.png')}}" alt="" width="30" height="24">
      <a class="navbar-brand text-white" href="{{ url_for('views.home') }}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"></button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link text-white" href="{{ url_for('views.register') }}">Register</a>
          <a class="nav-link text-white" href="{{ url_for('admin.index') }}">Admin</a>
        </div>
      </div>

      <!-- NAVBAR FORM SEARCH -->
      {% if index == True %}
        <form class="d-flex" method="POST">
          <input class="form-control me-2"  name="search_form" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>
      {% endif %}
    </div>
</nav>

{% endblock%} 


{% block content %}  {% endblock %}

<!-- FOOTER -->

{% block footer %}
<footer class=" mt-5 p-4 text-light"> 
  <p class="text-center border-top p-1">© 2021 Company, Inc</p>
</footer> 

{% endblock %} 

{% block scripts %}

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
{% endblock %}

lattes_site/templates/index.html
<!-- Extendendo o Template Base -->
{% extends 'base.html' %}

<!-- Setando um Valor para variavel index -->
{% set index = True%} 

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
  </head>
  <body>

      {% block content%} 

      <!-- Pegar e Mostrar as flash messages-->
      {% with messages = get_flashed_messages() %}  
      {% if messages %}   
            <div class="alert alert-success alert-dismissible fade show w-50 text-center mt-5" role="alert">
              <strong>Success Register</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
      {% endif %}  
     {% endwith %}

    <!-- Carrousel -->
      <div class="container-fluid">
        <div id="Main_Carousel" class="carousel slide" data-bs-ride="carousel">

          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>

          <div class="carousel-inner">
            <div class="carousel-item active">

              <img src="{{url_for('static', filename='images/home/flora.png')}}" class="d-block w-100" alt="Noticia-1">
              <div class="carousel-caption d-none d-md-block text-light">
                <h5>A Flora do Brasil 2020 lança seus dados</h5>
                <p class="text-center me-3 ms-3 ">Plataforma de dados e publicação online contam com o apoio do CNPq e reúnem informações necessárias para a identificação de todas as plantas nativas do país, além de imagens das plantas, algas e fungos brasileiros</p>
                <a href="https://www.gov.br/cnpq/pt-br/assuntos/noticias/pesquisa-do-dia/a-flora-do-brasil-2020-lanca-seus-dados" class="btn btn-info" role="button">Visitar</a>
              </div>

            </div>
            <div class="carousel-item">
              <img src="{{url_for('static', filename='images/home/ifc_2.jpg')}}" class="d-block w-100" alt="Noticia-2">
              <div class="carousel-caption d-none d-md-block text-light">
                <h5>IFC Concórdia produzirá respiradores de baixo custo</h5>
                <p class=" text-center me-3 ms-3">Concórdia poderá construir de 80 a 100 respiradores e entregá-los à comunidade até agosto. Isso porque o projeto para produção de um modelo de respirador mecânico foi aprovado pelo CONIF</p>
                <a href="https://noticias.concordia.ifc.edu.br/2020/05/27/ifc-concordia-produzira-respiradores-de-baixo-custo/" class="btn btn-info" role="button">Visitar</a>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{{url_for('static', filename='images/home/quimica_2.png')}}" class="d-block w-100" alt="Noticia-3">
              <div class="carousel-caption d-none d-md-block text-light">
                <h5>MEC prevê corte de R$ 4,2 bilhões no orçamento para 2021</h5>
                <p class="text-center me-3 ms-3">Previsão para o ano que vem reduz em 18,2% as despesas não obrigatórias, informou o Ministério da Educação</p>
                <a href="https://g1.globo.com/educacao/noticia/2020/08/10/orcamento-do-mec-preve-corte-de-r-42-bilhoes-para-2021.ghtml" class="btn btn-info" role="button">Visitar</a>
              </div>
            </div>
          </div>

          <button class="carousel-control-prev" type="button" data-bs-target="#Main_Carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#Main_Carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>

      <!-- NEWS CARDS -->

      <div class="container mt-5">
        <h1>Noticias</h1>
        <div class="Main-Cards d-flex justify-content-between mt-4">
          <div class="card">
            <img src="{{url_for('static', filename='images/home/talaska.jpg')}}" class="card-img-top" alt="renan">
            <div class="card-body">
              <h5 class="card-title">Ainda existem latifúndios no Brasil?</h5>
              <p class="card-text">Professor do IFTO publica livro sobre espaço agrário brasileiro. O livro é resultado da tese de Doutorado.</p>
              <a href="https://www.folhadobico.com.br/araguatins-professor-do-ifto-publica-livro-sobre-espaco-agrario-brasileiro/" class="btn btn-primary">Ver Mais</a>
            </div>
          </div>

          <div class="card">
            <img src="{{url_for('static', filename='images/home/repelentes.jpg')}}" class="card-img-top" alt="renan">
            <div class="card-body">
              <h5 class="card-title">Pesquisadores da UFRN</h5>
              <p class="card-text">Uma tecnologia desenvolvida na Universidade Federal do Rio Grande do Norte (UFRN) permite transformar um material para que ele passe a repelir a água.</p>
              <a href="https://g1.globo.com/rn/rio-grande-do-norte/noticia/2021/10/12/pesquisadores-da-ufrn-desenvolvem-tecnologia-capaz-de-fazer-materiais-repelirem-agua.ghtml" class="btn btn-primary">Ver Mais</a>
            </div>
          </div>

          
          <div class="card">
            <img src="{{url_for('static', filename='images/home/vacina_2.jpg')}}" class="card-img-top" alt="renan">
            <div class="card-body">
              <h5 class="card-title">Vacina sem Dor</h5>
              <p class="card-text">esquisadores da Holanda estão desenvolvendo uma tecnologia de laser para obter injeções sem agulha e "praticamente indolores", o que qualificam como um avanço que diminuirá o medo e reduzirá as barreiras de campanhas de vacinação.
              </p>
              <a href="https://noticias.r7.com/tecnologia-e-ciencia/pesquisadores-holandeses-criam-injecao-sem-agulha-e-sem-dor-13102021" class="btn btn-primary">Ver Mais</a>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}
  </body>
</html>

lattes_site/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

    <!-- Pegar e Mostrar as flash messages-->
    {% with messages = get_flashed_messages() %}  
      {% if messages %}  
             
            <div class="alert alert-danger alert-dismissible fade show w-50 text-center mt-5" role="alert">
              <strong>Something goes Wrong. Maybe the User or Email alredy exist</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
  
      {% endif %}  
     {% endwith %}


<div class="container mt-5 d-flex"> 
    <img src="{{url_for('static', filename='images/form/form_form.svg')}}" class="form_image" alt="form">
    <form class="form form-horizontal w-100 ms-2" method="post" role="form">

        <!-- Adicionando os formulários-->

        <h2>Registre-se</h2> 
        {{ form.hidden_tag() }} 
        {{ wtf.form_field(form.name)}}
        {{ wtf.form_field(form.email)}}
        {{ wtf.form_field(form.course)}}
        {{ wtf.form_field(form.formation)}}        
        {{ wtf.form_field(form.idiom)}}
        {{ wtf.form_field(form.address)}}

        <button class="btn btn-primary w-100 mt-3" type="submit" style = "background-color: #003B73;">Submit</button>

    </form>
</div>
{% endblock %}

lattes_site/templates/user.html
{% extends 'base.html' %}

{% block content %}

<div class="container d-flex justify-content-between mt-5"> 
    
    <img src="{{url_for('static', filename='images/user/user.png')}}" class="rounded-circle border border-dark w-50" alt="photo">
    
    <div class="container ms-4">
        <h1 class="text-center">{{user.name}}</h1>

        <h3>Formação:</h3>
        <p class=" p-2 ">{{user.course}} - {{user.formation}}</p>

        <h3>Email:</h3>
        <p class=" p-2 ">{{user.email}}</p>

        <h3>idioma:</h3>
        <p class=" p-2">Inglês - {{user.idiom}}</p>

        <h3>Endereço:</h3>
        <p class=" p-2">{{user.address}}</p>
    </div>

</div>

{% endblock %}